-- Drop tables
DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS Password;
DROP TABLE IF EXISTS Application;
DROP TABLE IF EXISTS Activity;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Status;
